
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/ruchir-panchamukhi/terraform-modules.git//modules/ec2"
}

#include "root" {
#  path = find_in_parent_folders()
#}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: AMI ID
  # Type: string
  ami_id = "ami-0ebd9b6d95de445f2" # TODO: fill in value

  # Description: Key Pair name created in AWS
  # Type: string
  key_name = "gha" # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable instance_type did not define a description)
  # Type: (variable instance_type does not define a type)
  # instance_type = "t2.micro"

}
