name: SSH into EC2 and Print Hello World

on:
  workflow_dispatch:

jobs:
  ssh-to-ec2:
    runs-on: self-hosted, ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create SSH key file
        run: |
         printf "%s" "${{ secrets.EC2_SSH_KEY }}" > key.pem
         chmod 600 key.pem

      - name: SSH into EC2 and run command
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "echo Hello World from GitHub Actions!"
